"""SLC engine: consumes prices from every configured source, generates
signals, executes them on the paper broker or via live EA commands, and
manages open trades (TP1 -> break-even -> structure trail).

Prices arrive two ways and are merged into one book: pushed by the MT5 EA
(`ingest_feed`) and polled from venue adapters (`refresh_venue_prices`).
Each quote carries the source that produced it and the instant it was true,
because staleness belongs to a SOURCE — the MT5 EA going quiet must cost you
the symbols it quotes and nothing else, and a deployment with no MT5 at all
must never wait for one.

Runs as a daemon thread started by server.py. All mutable runtime
parameters come from storage.settings (dashboard- and agent-tunable).
"""
import json
import math
import re
import threading
import time
from types import MappingProxyType
from typing import Any, Dict, List, Optional, Tuple

import decisions
import exposure
import instruments
import sessions
import storage
import strategy
import strategies
from strategy import MODE_TFS
try:
    import tv_context as _tv
    _TV_AVAILABLE = True
except ImportError:
    _TV_AVAILABLE = False
try:
    import news_calendar as _news_cal          # Phase 3 blackout gate
    _NEWS_CAL_AVAILABLE = True
except ImportError:
    _NEWS_CAL_AVAILABLE = False
try:
    import venues as _venues                   # venue registry (credentials in the DB)
    _VENUES_AVAILABLE = True
except ImportError:                            # optional: no venue kind installed
    _VENUES_AVAILABLE = False

# Smallest position that can actually be halved at TP1. The live path already
# gates its partial close on this (0.01 lots cannot be split), so paper must model
# the same limit or the sample that opens the promotion gate is generated by a fill
# the first live weeks - run at minimum size by design - structurally cannot produce.
MIN_PARTIAL_LOTS = 0.02

TF_SECONDS = {"15m": 900, "30m": 1800, "1h": 3600,
              "2h": 7200, "4h": 14400, "1d": 86400}

# Price provenance and staleness.
#
# The loop used to read "the MT5 EA has not posted for 60s" as "the world has
# stopped" and skipped the whole cycle — including stop management on positions
# it had opened itself somewhere else entirely. Staleness is a property of a
# SOURCE, never of the engine, so it is recorded per source and judged per
# symbol at the point of use. MT5 is now one source among several
# (docs/ARCHITECTURE-V3.md), and on a node that has none the engine must not
# spend its life waiting for a feed that is never coming.
MT5_SOURCE = "mt5"
MT5_PRICE_MAX_AGE_S = 60        # the EA pushes every 5s; 12 missed pushes is dead
# How far in the FUTURE a quote's stamp may sit and still be believed. Beyond
# this it is a clock problem, not a fresh price, and a clock problem must not
# read as permanently fresh.
MAX_CLOCK_SKEW_S = 1.0
VENUE_PRICE_MAX_AGE_S = 90      # venues are polled at the engine's own cadence

# Venues are polled on their OWN thread at this cadence, never inside the
# engine cycle. See _venue_poll_loop.
VENUE_POLL_INTERVAL_S = 10


# --------------------------------------------------------------------
# Shared live state: pushed by the EA, polled from venues (guarded by
# _feed_lock). "sources" is the per-source health the staleness rails read.
# --------------------------------------------------------------------
class _PriceBook(dict):
    """feed_state["prices"]. Stamps provenance at the WRITE layer.

    Every rail downstream assumes a quote in this book knows where it came
    from and when it was true. That guarantee used to depend on every writer
    remembering to stamp, and `price_state` carried an explicit branch that
    handed an unstamped record back as age=None / fresh=True / reachable=True —
    permanently tradable — with a comment conceding the branch existed for test
    fixtures. CONTRIBUTING is explicit that a rule which can be bypassed by
    forgetting to call something is not implemented, so the container enforces
    it and `price_state` now fails closed instead of excusing it.

    Provenance for an unattributed write comes from what instruments/venues
    already declare (`_declared_source`), never from what would make a trade
    go through, and the stamp is the real clock — so such a quote ages out on
    the same schedule as any other and can never be permanently tradable.

    Locking: the stamping path touches feed_state["sources"], so it inherits
    _write_price_locked's contract — the caller holds _feed_lock. Every writer
    in this module already stamps, so that path only runs for a write that came
    from outside it."""

    def __setitem__(self, symbol: str, rec: Any) -> None:
        if not isinstance(rec, dict):
            raise TypeError("price record must be a dict, got %r" % type(rec))
        try:
            src_t = float(rec.get("src_t") or 0)
        except (TypeError, ValueError):
            src_t = 0.0
        src = rec.get("src")
        if src and src_t > 0:
            # Fully attributed: the writer named a source and dated the quote.
            # That is a CLAIM, not an inference, and a claim is evidence that the
            # named source produced a print — so register it if we have never
            # heard of it. Never touch an EXISTING row: a direct write must not
            # resurrect a source a failed poll already marked unreachable.
            #
            # The distinction from the unattributed branch below is the whole
            # point. Believing a writer who says where a quote came from is
            # reasonable. Guessing on their behalf, and then declaring the guess
            # healthy, is what manufactured a feed out of nothing.
            if src not in (feed_state.get("sources") or {}):
                _source_rec_locked(src, rec.get("src_kind")
                                   or ("mt5" if src == MT5_SOURCE else "venue")
                                   ).update({"last_t": src_t, "reachable": True,
                                             "detail": ""})
            dict.__setitem__(self, symbol, rec)
            return
        now = time.time()
        rec = dict(rec)
        rec.setdefault("symbol", symbol)
        if not src:
            # Two claims were being made here and only one of them was true.
            #
            # Stamping the TIME is honest: we know when this record arrived,
            # whoever wrote it, so it ages on the same clock as everything else.
            #
            # Naming the SOURCE is not. Nobody said where this quote came from.
            # Inferring it from what instruments happens to declare is a guess,
            # and the previous version then wrote a health row for that guessed
            # source with reachable=True — so an unattributed write MANUFACTURED
            # a healthy feed. Verified directly: a bare price produced
            # source=mt5, fresh=True, reachable=True out of nothing, inside the
            # very rail added to stop quotes being trusted blindly.
            #
            # An unattributed quote is now recorded and kept, because it is
            # still worth showing an operator, but attributed to nobody.
            # price_state resolves that as unreachable and refuses entries. The
            # cost of being wrong this way is a missed trade; the cost of the
            # guess was trading against a feed that did not exist.
            rec["src"] = None
            rec["src_kind"] = "unattributed"
        if src_t <= 0:
            rec["src_t"] = now
        dict.__setitem__(self, symbol, rec)


class _FeedState(dict):
    """Keeps feed_state["prices"] a _PriceBook even when a caller replaces the
    whole book (`feed_state["prices"] = {...}`), which would otherwise drop the
    write-layer stamp on the floor."""

    def __setitem__(self, key: str, value: Any) -> None:
        if key == "prices" and not isinstance(value, _PriceBook):
            book = _PriceBook()
            for sym, rec in (value or {}).items():
                book[sym] = rec                     # re-stamped on the way in
            value = book
        dict.__setitem__(self, key, value)


_feed_lock = threading.Lock()
feed_state: Dict[str, Any] = _FeedState({
    "account": {}, "open_positions": [], "closed_today": [],
    "terminal": {}, "last_feed_t": 0, "last_bars_t": 0,
    "sources": {},
})
feed_state["prices"] = {}        # through __setitem__, so it becomes a _PriceBook

_stop = threading.Event()   # graceful shutdown; the loop exits after this cycle
_notify = None          # set by server.py -> notifier.send
_recent_keys: Dict[str, float] = {}   # signal dedup: key -> expiry ts
_last_info: Dict[str, Dict] = {}      # symbol|mode -> last analysis info
_tv_ctx: Dict[str, Any] = {}          # TradingView context snapshot (cached)
_tv_ctx_t: float = 0                  # timestamp of last TV context load


def stop() -> None:
    """Ask the loop (and the venue poller) to finish and exit. Nothing about
    stopping may close a position or move a stop: the venue keeps the stop it
    already has."""
    _stop.set()
    stop_venue_poller()


def set_notifier(fn) -> None:
    global _notify
    _notify = fn


def notify(msg: str) -> None:
    if _notify:
        try:
            _notify(msg)
        except Exception as e:           # never let telegram kill the engine
            print("notify error:", e)


# ------------------------------------------------------------ feed in
_open_spread: Dict[int, Dict[str, Any]] = {}


def _accum_px_window(p: Dict[str, Any]) -> None:
    """Track the worst exit-side price and max spread seen on the 5s feed
    BETWEEN 20s management cycles, so a spread blowout during news / session
    rollover still counts against open stops even if it lands between polls."""
    sym, bid, ask = p.get("symbol"), p.get("bid"), p.get("ask")
    if sym is None or bid is None or ask is None:
        return
    # prefer the EA's tick-accurate extremes for THIS push; fall back to quote
    t_min_bid = p.get("min_bid", bid)
    t_max_ask = p.get("max_ask", ask)
    point     = p.get("point") or 0.0
    spr_pts   = p.get("max_spread", p.get("spread", 0))
    spr_px    = (spr_pts * point) if point else abs(ask - bid)
    win = feed_state.setdefault("px_window", {})
    w = win.get(sym)
    if w is None:
        win[sym] = {"min_bid": t_min_bid, "max_ask": t_max_ask,
                    "max_spread": spr_px, "max_spread_pts": spr_pts}
    else:
        w["min_bid"] = min(w["min_bid"], t_min_bid)
        w["max_ask"] = max(w["max_ask"], t_max_ask)
        if spr_px > w["max_spread"]:
            w["max_spread"], w["max_spread_pts"] = spr_px, spr_pts


def _log_spread_event(tr: Dict[str, Any], max_spr: float,
                      max_spr_pts: float, spread_induced: bool) -> None:
    """Append a record so the real spread story of each stop is visible."""
    try:
        import json as _json, os as _os
        _os.makedirs("state", exist_ok=True)
        with open("state/spread_trace.jsonl", "a") as f:
            f.write(_json.dumps({
                "t": int(time.time()), "id": tr["id"], "symbol": tr["symbol"],
                "side": tr["side"], "mode": tr["mode"], "sl": tr["sl"],
                "max_spread_px": round(max_spr, 6), "max_spread_pts": max_spr_pts,
                "spread_induced": bool(spread_induced)}) + "\n")
    except Exception as e:
        print("spread-trace log error:", e)


# ------------------------------------------------- adapter error handling
# A third-party adapter's exception text is unbounded and attacker-adjacent:
# ccxt embeds the request it sent, so the string can carry an API key, a signed
# URL or a full header dump. That string used to be stored verbatim in the
# source record's `detail`, from where it reached signals.reason (persisted to
# the DB) and notify() (Telegram/Discord). Invariant 13 / CONTRIBUTING §Secrets
# forbid exactly that. Nothing derived from an exception MESSAGE may leave here;
# only a classification, and only from the exception's class name.
_ERR_CLASSES = (
    ("auth", ("authenticationerror", "permissiondenied", "invalidnonce",
              "invalidapikey", "accountsuspended", "forbidden", "unauthorized")),
    ("rate limit", ("ratelimit", "ddosprotection", "toomanyrequests")),
    ("timeout", ("timeout",)),
    ("network", ("networkerror", "connectionerror", "connectionreset",
                 "exchangenotavailable", "onmaintenance", "ssl", "socket")),
    ("bad symbol", ("badsymbol", "symbolnotfound", "badrequest")),
    ("exchange error", ("exchangeerror", "invalidorder", "notsupported",
                        "insufficientfunds")),
)
# Everything a source record's `detail` is ever allowed to say.
_DETAIL_LITERALS = frozenset(
    ["", "no quotes returned", "unclassified adapter error"]
    + [label for label, _ in _ERR_CLASSES])
# The class-name escape hatch, so an unmapped adapter failure is still
# diagnosable. A class name is an identifier written in library source, never
# response data, and it is length- and charset-bounded here regardless.
_DETAIL_CLASS_RE = re.compile(r"^adapter error \([A-Za-z0-9_]{1,40}\)$")


def classify_adapter_error(e: BaseException) -> str:
    """A bounded label for an adapter failure. Never the exception message."""
    cls = type(e).__name__
    low = cls.lower()
    for label, needles in _ERR_CLASSES:
        if any(n in low for n in needles):
            return label
    safe = "".join(ch for ch in cls if ch.isalnum() or ch == "_")[:40]
    return "adapter error (%s)" % (safe or "unknown")


def _safe_detail(detail: Any) -> str:
    """The write-layer rail for `detail`. A caller that hands this raw adapter
    text gets "unclassified adapter error" — the leak is closed by the store,
    not by every call site remembering to classify first."""
    d = "" if detail is None else str(detail)
    if d in _DETAIL_LITERALS or _DETAIL_CLASS_RE.match(d):
        return d
    return "unclassified adapter error"


# ------------------------------------------------- price sources
def _source_rec_locked(name: str, kind: str) -> Dict[str, Any]:
    """The health row for one price source. Caller holds _feed_lock."""
    srcs = feed_state.setdefault("sources", {})
    rec = srcs.get(name)
    if rec is None:
        rec = srcs[name] = {
            "name": name, "kind": kind, "last_t": 0.0, "reachable": False,
            "detail": "", "symbols": 0,
            "max_age_s": MT5_PRICE_MAX_AGE_S if kind == "mt5"
            else VENUE_PRICE_MAX_AGE_S,
        }
    rec["kind"] = kind
    return rec


def _set_source(name: str, kind: str, **fields: Any) -> Dict[str, Any]:
    if "detail" in fields:
        fields["detail"] = _safe_detail(fields["detail"])
    with _feed_lock:
        rec = _source_rec_locked(name, kind)
        rec.update(fields)
        return dict(rec)


def _write_price_locked(rec: Dict[str, Any], source: str, src_t: float,
                        kind: str = "venue") -> bool:
    """The ONLY writer of feed_state["prices"]. Caller holds _feed_lock.

    Every quote is stamped with the source it came from and the instant it was
    true. A rail that cannot tell WHERE a price came from cannot tell whether
    it is still worth acting on, and stamping at the write layer is the only
    way the answer does not depend on every caller remembering to."""
    sym = rec.get("symbol")
    bid, ask = rec.get("bid"), rec.get("ask")
    if not sym or bid is None or ask is None:
        return False
    prev = feed_state["prices"].get(sym)
    # An older print never overwrites a newer one, whatever source it arrived
    # from. This is exactly how a stale venue quote would masquerade as fresh:
    # by landing on top of a good one and inheriting its recency.
    if prev is not None and float(prev.get("src_t") or 0) > float(src_t):
        return False
    p = dict(rec)
    p["src"], p["src_t"], p["src_kind"] = source, float(src_t), kind
    feed_state["prices"][sym] = p
    _accum_px_window(p)              # capture intra-cycle spread + extremes
    return True


def merge_prices(records: List[Dict[str, Any]], source: str,
                 kind: str = "venue") -> int:
    """Merge quotes from a non-EA source into the same structure the EA writes,
    so every rail downstream sees one book and cannot tell (or care) which
    venue quoted it. Returns how many were accepted."""
    now = time.time()
    n = 0
    with _feed_lock:
        for r in records:
            t = r.get("src_t") or now
            if _write_price_locked(r, source, min(float(t), now), kind):
                n += 1
    return n


def ingest_feed(data: Dict[str, Any]) -> None:
    now = time.time()
    with _feed_lock:
        feed_state["account"] = data.get("account", {})
        feed_state["open_positions"] = data.get("open_positions", [])
        feed_state["closed_today"] = data.get("closed_today", [])
        feed_state["terminal"] = data.get("terminal", {})
        n = 0
        for p in data.get("prices", []):
            if _write_price_locked(p, MT5_SOURCE, now, kind="mt5"):
                n += 1
        feed_state["last_feed_t"] = now
        rec = _source_rec_locked(MT5_SOURCE, "mt5")
        rec.update({"last_t": now, "reachable": True, "detail": "", "symbols": n})


def ingest_bars(data: Dict[str, Any]) -> None:
    bars = data.get("bars", {})
    for symbol, tfs in bars.items():
        for tf, blist in tfs.items():
            if isinstance(blist, list) and blist:
                storage.store_bars(symbol, tf, blist)
    with _feed_lock:
        feed_state["last_bars_t"] = time.time()


def get_feed() -> Dict[str, Any]:
    with _feed_lock:
        return json.loads(json.dumps(feed_state))


def get_last_info() -> List[Dict]:
    return list(_last_info.values())


# ------------------------------------------------- staleness, per source
def source_state(name: str, now: Optional[float] = None) -> Dict[str, Any]:
    """Health of one price source: has it reported, how long ago, is it
    answering. A source nobody has ever heard from is not healthy — it is
    unknown, and unknown fails closed."""
    now = time.time() if now is None else now
    rec = (feed_state.get("sources") or {}).get(name)
    if rec is None:
        return {"name": name, "known": False, "fresh": False, "reachable": False,
                "age": None, "reason": "%s has never reported" % name}
    age = now - float(rec.get("last_t") or 0)
    lim = float(rec.get("max_age_s") or MT5_PRICE_MAX_AGE_S)
    fresh = bool(rec.get("last_t")) and age <= lim
    reason = ""
    if not rec.get("last_t"):
        reason = "%s has never reported" % name
    elif not fresh:
        reason = "%s feed stale (%.0fs old, limit %.0fs)" % (name, age, lim)
    elif not rec.get("reachable"):
        reason = "%s unreachable: %s" % (name, rec.get("detail") or "no detail")
    return {"name": name, "known": True, "fresh": fresh,
            "reachable": bool(rec.get("reachable")), "age": age,
            "kind": rec.get("kind"), "detail": rec.get("detail") or "",
            "symbols": rec.get("symbols") or 0, "reason": reason}


def price_state(symbol: str, now: Optional[float] = None) -> Dict[str, Any]:
    """What we know about the quote for one symbol, and how much of it we are
    entitled to believe."""
    now = time.time() if now is None else now
    p = feed_state["prices"].get(symbol)
    if not p:
        return {"price": None, "source": None, "age": None, "fresh": False,
                "reachable": False, "reason": "no live price"}
    src = p.get("src")
    rec = (feed_state.get("sources") or {}).get(src) if src else None
    try:
        src_t = float(p.get("src_t") or 0)
    except (TypeError, ValueError):
        src_t = 0.0
    if src_t <= 0:
        # No clock on the quote means no way to age it, and "I cannot tell how
        # old this is" must never come back as "fresh". This branch used to
        # return age=None / fresh=True / reachable=True — permanently tradable —
        # to accommodate test fixtures that wrote into the book directly. The
        # stamp is now enforced by _PriceBook at the write layer, so getting
        # here means a record reached the book some other way, and the honest
        # answer to unknown provenance is to stand aside.
        return {"price": None, "source": src, "age": None, "fresh": False,
                "reachable": False,
                "reason": "%s quote carries no timestamp — age unknown"
                          % (src or symbol)}
    age = now - src_t
    max_age = float((rec or {}).get("max_age_s") or MT5_PRICE_MAX_AGE_S)
    # Bounded at BOTH ends. "age <= max_age" alone reads a NEGATIVE age as fresh,
    # so a quote stamped in the future is fresh forever and never ages out - the
    # same permanently-tradable state this function was rewritten to remove,
    # reached from the other direction. A future stamp is not a fresh quote, it
    # is a clock problem: a venue with a fast clock, an NTP step, a VM resume.
    # Tolerate a second of skew, then stand aside and say why.
    fresh = -MAX_CLOCK_SKEW_S <= age <= max_age
    # A source with no health row is a source nobody has ever heard from. That
    # is unknown, not reachable — it used to read `True if rec is None`, so an
    # unregistered source was assumed to be answering.
    reachable = bool(rec) and bool(rec.get("reachable"))
    reason = ""
    if age < -MAX_CLOCK_SKEW_S:
        reason = ("%s quote is stamped %.0fs in the FUTURE — clock skew, not a "
                  "fresh price" % (src or "feed", -age))
    elif not fresh:
        reason = "%s price stale (%.0fs old, limit %.0fs)" % (
            src or "feed", age, max_age)
    elif not reachable:
        # `detail` is a bounded classification (see _safe_detail); the raw
        # adapter text it used to carry — and the doubled "unreachable:
        # unreachable:" prefix that came with it — are both gone.
        reason = ("%s unreachable: %s" % (src, rec.get("detail") or "no detail")
                  if rec else "%s has never reported" % (src or "unknown source"))
    return {"price": p, "source": src, "age": age, "fresh": fresh,
            "reachable": reachable, "reason": reason}


def price_if_fresh(symbol: str, now: Optional[float] = None):
    """The quote to MANAGE an open position with. Recency is the only test: a
    source that has since gone unreachable still told the truth about the last
    print it gave us, and a stop breached at that print was breached."""
    st = price_state(symbol, now)
    return (st["price"] if st["fresh"] else None), st["reason"]


def price_for_entry(symbol: str, now: Optional[float] = None):
    """The quote to OPEN on. Fresh AND from a source that is still answering:
    a venue we cannot reach is a venue we cannot trade, whatever its last
    print said."""
    st = price_state(symbol, now)
    if st["fresh"] and st["reachable"]:
        return st["price"], ""
    return None, st["reason"] or "no live price"


def mt5_configured() -> bool:
    """Is there an MT5 EA in this deployment at all?

    MT5 is no longer the primary path. On a Linux node there is no EA and never
    will be, so "wait for the EA" is not a safe default there — it is a
    permanent halt. An explicit setting wins; otherwise a feed that has ever
    arrived, in this process or a previous one, is the evidence."""
    try:
        flag = storage.get_setting("mt5_enabled", None)
    except Exception:
        flag = None
    if flag is not None:
        return bool(flag)
    if feed_state.get("last_feed_t"):
        return True
    try:
        return bool(storage.get_setting("ea_last_feed_t", 0))
    except Exception:
        return False


def feed_report(now: Optional[float] = None) -> Dict[str, Any]:
    """Per-source feed health — what replaced the single question "is the EA
    talking?" that used to gate the entire engine."""
    now = time.time() if now is None else now
    srcs = [source_state(n, now) for n in sorted(feed_state.get("sources") or {})]
    healthy = [s["name"] for s in srcs if s["fresh"] and s["reachable"]]
    degraded = [s for s in srcs if not (s["fresh"] and s["reachable"])]
    has_mt5 = mt5_configured()
    if has_mt5 and not any(s["name"] == MT5_SOURCE for s in srcs):
        degraded.append(source_state(MT5_SOURCE, now))
    if not srcs and not has_mt5:
        note = "no price source has reported yet (no MT5 configured)"
    elif not degraded:
        note = "sources ok: %s" % (", ".join(healthy) or "none")
    else:
        note = "; ".join([s["reason"] for s in degraded if s["reason"]]) or "degraded"
        if healthy:
            note = "%s (still live: %s)" % (note, ", ".join(healthy))
    # The poller runs off the cycle, so its own health has to be reported
    # explicitly: a wedged poll shows up here before the quotes it stopped
    # refreshing age out.
    vp = dict(feed_state.get("venue_poll") or {})
    if vp and now - float(vp.get("t") or 0) > 3 * VENUE_POLL_INTERVAL_S:
        note = "%s; venue poll last ran %.0fs ago" % (note, now - float(vp["t"]))
    return {"sources": srcs, "healthy": healthy,
            "degraded": [s["name"] for s in degraded],
            "mt5_configured": has_mt5, "venue_poll": vp, "note": note}


# ------------------------------------------------- declared routes
def _venue_cfgs() -> Dict[str, Dict[str, Any]]:
    """{name: config} for every registered venue. Never raises: a registry we
    cannot read declares nothing, and declaring nothing fails closed."""
    if not _VENUES_AVAILABLE:
        return {}
    try:
        return {v.get("name"): v for v in _venues.list_venues() if v.get("name")}
    except Exception as e:
        print("venue registry read error:", type(e).__name__)
        return {}


def declared_venues(symbol: str) -> List[str]:
    """Every REGISTERED venue that declares this symbol, from the same two
    declarations `venue_symbol_map` uses and no others: a venue config row's
    `symbols` list, and the instruments registry's `venue` column.

    Empty means nothing registered claims it — which is the MT5 case, because
    MT5 is not a venue row. More than one means the declarations disagree, and
    a disagreement about where an order goes is not something to average out."""
    cfgs = _venue_cfgs()
    if not cfgs:
        return []
    claims = set()
    for name, cfg in cfgs.items():
        for entry in (cfg.get("symbols") or []):
            if str(entry).partition(":")[0] == symbol:
                claims.add(name)
                break
    v = (instruments.get(symbol) or {}).get("venue")
    if v and v in cfgs:
        claims.add(v)
    return sorted(claims)


def _declared_source(symbol: str) -> str:
    """Who a quote for this symbol is presumed to have come from when the
    writer did not say. Unambiguous declaration wins; otherwise MT5, which is
    the default `instruments.seed_defaults()` writes and what
    `venue_symbol_map` already assumes for an unrouted symbol."""
    try:
        vs = declared_venues(symbol)
    except Exception:
        return MT5_SOURCE
    return vs[0] if len(vs) == 1 else MT5_SOURCE


def execution_route(symbol: str, src: Optional[str],
                    mode: str) -> Dict[str, Any]:
    """Where an order for `symbol`, priced by source `src`, is allowed to go.

    The order goes to the venue that quoted the price and nowhere else. Sizing
    a position off one venue's book and submitting it to another is not a
    routing inconvenience — it is a real fill, at the wrong broker, at a price
    that broker never showed. `try_execute` used to be provenance-blind and the
    live branch enqueued an MT5 `open_trade` unconditionally, so a symbol routed
    to a crypto venue produced exactly that.

    Returns {"ok", "route", "kind", "reason"}. Every refusal is a reason the
    caller records; none of them collapse into a benign default."""
    if not src:
        return {"ok": False, "route": None, "kind": None,
                "reason": "quote has no source — cannot tell which venue would fill it"}
    claims = declared_venues(symbol)
    if len(claims) > 1:
        return {"ok": False, "route": None, "kind": None,
                "reason": "%s is declared on more than one venue (%s) — refusing "
                          "to guess where the order goes" % (symbol, ", ".join(claims))}
    if claims and claims[0] != src:
        return {"ok": False, "route": None, "kind": None,
                "reason": "%s is declared on %s but quoted by %s — price and "
                          "execution venue must be the same"
                          % (symbol, claims[0], src)}
    if claims:
        route, kind = claims[0], "venue"
    elif src == MT5_SOURCE:
        route, kind = MT5_SOURCE, "mt5"
    else:
        # src names a venue that no longer declares the symbol (config edited
        # between the poll and the fill). Standing aside costs an opportunity.
        return {"ok": False, "route": None, "kind": None,
                "reason": "%s was quoted by %s, which no longer declares it"
                          % (symbol, src)}
    if mode == "live":
        # The EA is the only wired execution path in this file. A venue adapter
        # can quote and it can be reconciled against, but nothing here submits
        # an order to one (docs/ARCHITECTURE-V3.md §5 Increment 6 gates that
        # behind supports_attached_stop and the host-continuity rail). Until
        # then a live entry on a venue-routed symbol has nowhere to go, and the
        # honest response is to refuse rather than send it to MT5.
        if kind != "mt5":
            return {"ok": False, "route": route, "kind": kind,
                    "reason": "no live execution path to %s (the MT5 EA is the "
                              "only wired venue) — refusing the entry" % route}
        if not mt5_configured():
            return {"ok": False, "route": route, "kind": kind,
                    "reason": "live entry routed to MT5 but no EA has ever "
                              "reported in this deployment"}
    return {"ok": True, "route": route, "kind": kind, "reason": ""}


# ------------------------------------------------- venue-sourced prices
_venue_meta_cache: Dict[str, Dict[str, Any]] = {}
_VENUE_META_TTL_S = 3600
# A FAILED metadata lookup is retried within the minute, not cached for an hour.
_VENUE_META_FAIL_TTL_S = 60


def _match_back(want: Dict[str, str], venue_symbol: str) -> Optional[str]:
    """Venue spelling -> engine symbol (BTC/USDT -> BTCUSD)."""
    if venue_symbol in want:
        return want[venue_symbol]
    norm = venue_symbol.replace("/", "").replace("-", "").upper()
    for k, v in want.items():
        if k.replace("/", "").replace("-", "").upper() == norm:
            return v
    return None


def _venue_tick_meta(vname: str, adapter: Any, symbol: str) -> Dict[str, Any]:
    """tick_size / tick_value for a venue symbol, so calc_lots sizes a venue
    fill with the same arithmetic it uses for an MT5 fill. Metadata we cannot
    get is left absent rather than guessed: calc_lots then returns zero lots
    and the entry is refused, which is the honest answer to "I cannot size
    this"."""
    key = "%s|%s" % (vname, symbol)
    hit = _venue_meta_cache.get(key)
    if hit:
        # A SUCCESS is cached for the full TTL: instrument increments change
        # rarely. A FAILURE is retried within the minute. Caching a failure for
        # an hour meant one transient error left every position on that symbol
        # unvaluable — and therefore new entries halted — long after the venue
        # had recovered.
        ttl = _VENUE_META_TTL_S if hit["meta"] else _VENUE_META_FAIL_TTL_S
        if time.time() - hit["t"] < ttl:
            return dict(hit["meta"])
    meta: Dict[str, Any] = {}
    try:
        m = adapter.symbol_meta(symbol)
        ts = float(getattr(m, "tick_size", 0) or 0)
        tv = ts * float(getattr(m, "contract_size", 1.0) or 1.0)
        # Both must be finite and positive. NaN passes "> 0" as False so it is
        # excluded here, but inf would pass, and an infinite tick_value silently
        # poisons every sizing and P&L calculation downstream.
        if ts > 0 and tv > 0 and math.isfinite(ts) and math.isfinite(tv):
            meta = {"tick_size": ts, "point": ts, "tick_value": tv}
    except Exception:
        meta = {}
    _venue_meta_cache[key] = {"t": time.time(), "meta": meta}
    return dict(meta)


def venue_symbol_map(symbols: List[str]) -> Dict[str, Dict[str, str]]:
    """{venue_name: {venue_symbol: engine_symbol}}.

    Two declared routes, no inference: the instruments registry's `venue`
    column, and an optional `symbols` list on the venue's own config row
    ("BTCUSD" or "BTCUSD:BTC/USDT"). A symbol nobody routed stays where it
    was — inventing a venue for it would be the engine guessing where an
    order goes."""
    out: Dict[str, Dict[str, str]] = {}
    if not _VENUES_AVAILABLE or not symbols:
        return out
    cfgs = _venue_cfgs()
    if not cfgs:
        return out
    want = set(symbols)
    for sym in symbols:
        meta = instruments.get(sym) or {}
        vname = meta.get("venue") or MT5_SOURCE
        if vname in cfgs:
            out.setdefault(vname, {})[meta.get("venue_symbol") or sym] = sym
    for name, cfg in cfgs.items():
        for entry in (cfg.get("symbols") or []):
            sym, _, vsym = str(entry).partition(":")
            if sym in want:
                out.setdefault(name, {})[vsym or sym] = sym
    return out


def refresh_venue_prices(symbols: List[str]) -> Dict[str, str]:
    """Poll every configured venue that quotes one of `symbols` and merge the
    result into the shared book with provenance attached.

    NEVER call this from the engine cycle: `stream_prices` is an unbounded
    synchronous network call and stop management must not wait behind it
    (_venue_poll_loop is the only production caller).

    Failures are contained to the venue that failed: an exchange that is down
    costs you the symbols it quotes and nothing else. Returns {venue: label},
    where the label is a CLASSIFICATION — the adapter's own exception text is
    never returned, stored or forwarded (see classify_adapter_error)."""
    errors: Dict[str, str] = {}
    for vname, want in venue_symbol_map(symbols).items():
        try:
            ad = _venues.adapter(vname)
            ticks = list(ad.stream_prices(list(want)))
        except Exception as e:
            # No "unreachable: " prefix here: source_state adds one, and the two
            # used to compound into "unreachable: unreachable: <raw text>".
            errors[vname] = classify_adapter_error(e)
            _set_source(vname, "venue", reachable=False, detail=errors[vname])
            continue
        now = time.time()
        recs: List[Dict[str, Any]] = []
        for t in ticks:
            sym = _match_back(want, str(getattr(t, "symbol", "") or ""))
            if not sym:
                continue
            try:
                bid, ask = float(t.bid), float(t.ask)
            except (TypeError, ValueError):
                continue
            if bid <= 0 or ask <= 0 or ask < bid:
                continue
            rec: Dict[str, Any] = {"symbol": sym, "bid": bid, "ask": ask,
                                   "src_t": float(getattr(t, "ts", 0) or now)}
            rec.update(_venue_tick_meta(vname, ad, sym))
            pt = float(rec.get("point") or 0)
            rec["spread"] = int(round((ask - bid) / pt)) if pt > 0 else 0
            recs.append(rec)
        n = merge_prices(recs, vname, kind="venue")
        if n:
            _set_source(vname, "venue", reachable=True, detail="",
                        symbols=n, last_t=now)
        else:
            # A venue that answers with nothing is a venue we cannot price
            # against. Standing aside on its symbols costs an opportunity;
            # trading them off the last print it gave us costs money.
            errors[vname] = "no quotes returned"
            _set_source(vname, "venue", reachable=False,
                        detail="no quotes returned")
    return errors


# ------------------------------------------- venue polling, off the hot loop
# The original defect on this branch was stop management blocked behind a feed.
# It came back as a blocking call instead of a `continue`: refresh_venue_prices
# sat AHEAD of manage_open_trades in the cycle, and one wedged exchange
# (load_markets plus a fetch_ticker per symbol, each at ccxt's 15s timeout)
# delays every breakeven move, every trail and every paper stop evaluation by
# however long the exchange takes to answer. Managing a position we already
# hold must never wait on fetching prices for one we do not.
#
# So the poll owns a thread. The engine cycle publishes the symbol list it
# wants priced and reads whatever is in the book; if the poller is wedged, the
# quotes it stopped refreshing age out and the staleness rails refuse entries
# on them — which is the correct fail-closed outcome and costs no management.
_venue_poll_stop = threading.Event()
_venue_poll_thread: Optional[threading.Thread] = None
_venue_want_lock = threading.Lock()
_venue_want: List[str] = []


def set_venue_symbols(symbols: Any) -> None:
    """Publish the symbols the poller should keep priced. Cheap and
    non-blocking: it is called from the engine cycle."""
    global _venue_want
    with _venue_want_lock:
        _venue_want = sorted({str(s) for s in symbols})


def _venue_poll_loop(interval: float) -> None:
    while not _venue_poll_stop.is_set():
        with _venue_want_lock:
            syms = list(_venue_want)
        t0 = time.time()
        errs: Dict[str, str] = {}
        try:
            if syms:
                errs = refresh_venue_prices(syms)
        except Exception as e:                 # a dead poller must not be silent
            errs = {"poller": classify_adapter_error(e)}
        feed_state["venue_poll"] = {
            "t": t0, "took_s": round(time.time() - t0, 3),
            "symbols": len(syms), "errors": errs}
        _venue_poll_stop.wait(interval)


def start_venue_poller(interval: float = VENUE_POLL_INTERVAL_S) -> None:
    global _venue_poll_thread
    t = _venue_poll_thread
    if t is not None and t.is_alive():
        return
    _venue_poll_stop.clear()
    _venue_poll_thread = threading.Thread(target=_venue_poll_loop,
                                          args=(float(interval),),
                                          name="venue-poller", daemon=True)
    _venue_poll_thread.start()


def stop_venue_poller(join_s: float = 0.0) -> None:
    """Ask the poller to exit. Like stop(), this never touches a position."""
    _venue_poll_stop.set()
    t = _venue_poll_thread
    if t is not None and join_s:
        t.join(timeout=join_s)


# ----------------------------------------------------------- params
def params() -> Dict[str, Any]:
    s = storage.all_settings()
    out = {
        "trading_mode": s.get("trading_mode", "paper"),
        "modes": s.get("modes", ["intraday", "swing"]),
        "risk_pct": float(s.get("risk_pct", 1.0)),
        "b_setup_risk_factor": float(s.get("b_setup_risk_factor", 0.5)),
        "min_rr": float(s.get("min_rr", 2.0)),
        "atr_buffer": float(s.get("atr_buffer", 0.35)),
        "vol_mult": float(s.get("vol_mult", 0.0)),
        "max_concurrent": int(s.get("max_concurrent", 2)),
        "max_concurrent_per_class": int(s.get("max_concurrent_per_class", 2)),
        "max_correlated": int(s.get("max_correlated", 3)),
        "max_bucket_exposure": float(s.get("max_bucket_exposure", 2.0)),
        "halt_new_entries": bool(s.get("halt_new_entries", False)),
        "daily_stop_pct": float(s.get("daily_stop_pct", 2.0)),
        "weekly_stop_pct": float(s.get("weekly_stop_pct", 5.0)),
        "min_grade": s.get("min_grade", "B"),
        "regime_max": float(s.get("regime_max", 2.5)),
        "regime_b_ban": float(s.get("regime_b_ban", 1.5)),
        "max_spread_frac": float(s.get("max_spread_frac", 0.10)),
        "enabled_pairs": s.get("enabled_pairs", []),
        "watch_pairs": s.get("watch_pairs", []),
        "agent_disabled_pairs": s.get("agent_disabled_pairs", []),
        "agent_disabled_modes": s.get("agent_disabled_modes", []),
        "paper_balance": float(s.get("paper_balance", 10000.0)),
    }
    # strategy enable flags (strategy_<name>_enabled) flow through to the plugin
    # registry; default-on, so SLC stays on exactly as before and a new strategy
    # is picked up here automatically once its setting is seeded.
    for k, v in s.items():
        if k.startswith("strategy_") and k.endswith("_enabled"):
            out[k] = bool(v)
    return out


# ------------------------------------------------------------ sizing
def calc_lots(symbol: str, entry: float, sl: float, risk_amount: float):
    """Broker-exact sizing from tick_value/tick_size pushed by the EA.
    Returns (lots, actual_risk) so the caller can record the TRUE risk
    after lot rounding (min-lot floors can otherwise overstate it)."""
    p = feed_state["prices"].get(symbol)
    if not p:
        return 0.0, 0.0
    tick_value = p.get("tick_value") or 0
    tick_size = p.get("tick_size") or 0
    if tick_value <= 0 or tick_size <= 0:
        return 0.0, 0.0
    loss_per_lot = abs(entry - sl) / tick_size * tick_value
    if loss_per_lot <= 0:
        return 0.0, 0.0
    lots = max(0.01, int(risk_amount / loss_per_lot * 100) / 100.0)
    return lots, round(lots * loss_per_lot, 2)


# ------------------------------------------------- unrealized P&L
def trade_upnl(tr: Dict) -> Optional[float]:
    """Unrealized P&L of an open trade. Live trades use the broker's own
    number (includes swap/commission); paper trades are marked to the
    exit side of the book (bid for longs, ask for shorts)."""
    if tr["mode"] == "live":
        pos = next((x for x in feed_state["open_positions"]
                    if x.get("ticket") == tr["ticket"]
                    or "SLC#%d" % tr["id"] in (x.get("comment") or "")), None)
        if pos is not None:
            return round((pos.get("unrealized_pnl") or 0) + (pos.get("swap") or 0), 2)
    # Recency is REQUIRED here, and it was not checked. This function read the
    # book raw, so a print frozen an hour ago valued the position, and that value
    # flows into _open_pnl -> loss_limits_hit. The daily and weekly kill switches
    # were therefore marking the book against a dead quote: a position that had
    # since moved hard against us still looked exactly as it did when the feed
    # died, and the stop that should have fired did not.
    #
    # Management deliberately still acts on a stale print, because a stop
    # breached at the last real price WAS breached - that is price_if_fresh's
    # job, and de-risk-only is enforced there. But VALUING the book is a
    # different question, and the honest answer on a dead feed is "I cannot".
    st = price_state(tr["symbol"])
    if not st["fresh"]:
        return None
    p = st["price"]
    if not p:
        return None
    tick_value = p.get("tick_value") or 0
    tick_size = p.get("tick_size") or 0
    if tick_value <= 0 or tick_size <= 0:
        return None
    cur = p["bid"] if tr["side"] == "buy" else p["ask"]
    direction = 1 if tr["side"] == "buy" else -1
    pnl = (cur - tr["entry"]) * direction / tick_size * tick_value * tr["lots"]
    if tp1_partial_taken(tr):
        # half was banked at +1R: value it from price distance (exact),
        # not from the recorded risk_amount
        banked = abs(tr["entry"] - tr["initial_sl"]) / tick_size * tick_value * tr["lots"]
        pnl = pnl * 0.5 + banked * 0.5
    return round(pnl, 2)


def open_pnl_total() -> Tuple[float, int]:
    """Marked value of the whole open book, and how much of it could not be
    valued. The SECOND instance of the `or 0` defect, found by grepping for the
    first: this fed the equity sample, so an unvaluable position quietly made
    equity look better than it was, and that equity is what the drawdown
    forensics and the equity curve are computed from. A wrong sample there is
    worse than a missing one, because it is indistinguishable from a real one."""
    total, unvalued = 0.0, 0
    for t in storage.open_trades():
        v = trade_upnl(t)
        if v is None:
            unvalued += 1
        else:
            total += v
    return round(total, 2), unvalued


# ----------------------------------------------------- loss limits
def round_turn_cost(tr: Dict[str, Any], price: float) -> float:
    """What the round turn costs, in account currency. Never negative.

    Paper P&L was pure price movement while live P&L reads profit + commission +
    swap off the broker deal. So the 50-trade sample that opens the promotion gate
    was measured GROSS and the live results it is meant to predict are NET. At a
    profit factor near 1.1 that difference is the whole edge, and the gate would
    happily certify a strategy whose net expectancy is negative.

    Three components, because the venues charge differently:
      per-lot commission   how MT5 brokers usually bill FX and metals
      taker fee on notional  how every crypto exchange bills, 0.10% to 1.20%
      slippage             a fixed haircut per side; entering and exiting at the
                           mid price is a fiction no live account gets

    Defaults are deliberately non-zero. A cost model that defaults to free is the
    same bug in a nicer suit."""
    s = storage.all_settings()
    p = feed_state["prices"].get(tr["symbol"], {})
    tick_size = p.get("tick_size") or 0
    tick_value = p.get("tick_value") or 0
    lots = float(tr.get("lots") or 0)

    commission = float(s.get("paper_commission_per_lot", 7.0)) * lots

    taker = float(s.get("paper_taker_fee_pct", 0.0))
    notional = 0.0
    if taker and tick_size > 0 and tick_value > 0:
        # value of a 1.0 price move, scaled to the traded price on both sides
        per_price_unit = tick_value / tick_size * lots
        notional = (abs(tr.get("entry") or 0) + abs(price or 0)) * per_price_unit
    fee = notional * taker / 100.0

    slip_pts = float(s.get("paper_slippage_points", 1.0))
    slippage = 0.0
    if slip_pts and tick_size > 0 and tick_value > 0:
        slippage = 2 * slip_pts * tick_value * lots      # entry side and exit side

    return round(max(0.0, commission + fee + slippage), 4)


def tp1_partial_taken(tr: Dict[str, Any]) -> bool:
    """Was half the position ACTUALLY banked at TP1, or only the stop moved?

    tp1_done means "price reached +1R, stop is now at breakeven" and applies in
    both modes. Banking 50% is a separate question, because a 0.01-lot position
    cannot be halved. Paper used to assume the partial always happened; live
    refuses it below MIN_PARTIAL_LOTS. Same predicate for both now, so paper P&L
    matches what a minimum-size live account would really have realised."""
    return bool(tr["tp1_done"]) and (tr["lots"] or 0) >= MIN_PARTIAL_LOTS


def _pnl_since(mode: str, since_ts: int) -> float:
    row = storage.query_one(
        "SELECT COALESCE(SUM(pnl),0) s FROM trades "
        "WHERE mode=? AND status='closed' AND exit_time>=?", (mode, since_ts))
    return row["s"] if row else 0.0


def _open_pnl(mode: str) -> Tuple[float, int]:
    """Open P&L, and how many positions could NOT be valued.

    The count is the point. This used to be sum(trade_upnl(t) or 0), which turns
    an UNKNOWN into a ZERO, and zero reads as "that position is flat" - the most
    reassuring possible answer to a question we could not answer. A venue whose
    symbol_meta call failed writes a price record with no tick_value, trade_upnl
    then returns None for every position quoted from it, and the open drawdown
    feeding the daily and weekly kill switches becomes exactly nothing while the
    book is underwater. Invariant 9 defeated, silently, by an `or 0`.

    Callers get the count and must decide. Nobody may collapse it back to one
    number."""
    total, unknown = 0.0, 0
    for t in storage.open_trades(mode):
        v = trade_upnl(t)
        if v is None:
            unknown += 1
        else:
            total += v
    return round(total, 2), unknown


def _broker_offset() -> float:
    term = feed_state.get("terminal", {})
    return (term.get("time_local") or 0) - (term.get("time_utc") or 0)


def loss_limits_hit(mode: str, balance: float, p: Dict) -> Optional[str]:
    """Daily/weekly kill switches. The loss 'day' follows the broker clock
    (statements cut there, not at UTC midnight), and OPEN drawdown counts
    against the stop — being -2% underwater on open positions halts new
    entries just as surely as -2% realized. Open profit never offsets
    realized losses (conservative by construction)."""
    if balance <= 0:
        return None
    day0, week0 = sessions.day_week_start("broker", broker_offset_s=_broker_offset())
    open_pnl, unvalued = _open_pnl(mode)

    # A position we cannot value is not a position worth nothing. If any open
    # trade has no usable quote, the drawdown feeding these stops is understated
    # by an unknown amount, so the honest reading of "am I past my daily stop?"
    # is "I cannot tell" - and the fail-closed answer to that is to stop opening
    # new ones. This does NOT touch existing positions; their stops are managed
    # on the last confirmed price by manage_open_trades.
    if unvalued:
        return ("cannot value %d open position%s (no usable quote) — open "
                "drawdown is unknown, so new entries stand aside"
                % (unvalued, "" if unvalued == 1 else "s"))

    open_dd = min(0.0, open_pnl)
    if _pnl_since(mode, day0) + open_dd <= -balance * p["daily_stop_pct"] / 100:
        return "daily stop (-%.1f%%) hit" % p["daily_stop_pct"]
    if _pnl_since(mode, week0) + open_dd <= -balance * p["weekly_stop_pct"] / 100:
        return "weekly stop (-%.1f%%) hit" % p["weekly_stop_pct"]
    return None


def loss_governor(mode: str) -> float:
    """Playbook §10.3: after 3 consecutive losses, halve risk until 2
    consecutive wins. Derived from the trades table (restart-safe — no
    counters to lose)."""
    # pnl IS NOT NULL matters: "(r['pnl'] or 0) < 0" reads NULL as a WIN, so a
    # closed row that never got its pnl written would reset the loss streak and
    # silently un-halve risk. Invariant 10 must not be defeated by bad data.
    rows = storage.query(
        "SELECT pnl FROM trades WHERE mode=? AND status='closed' "
        "AND pnl IS NOT NULL ORDER BY exit_time DESC LIMIT 50", (mode,))
    halved, consec_loss, consec_win = False, 0, 0
    for r in reversed(rows):                       # oldest -> newest
        if (r["pnl"] or 0) < 0:
            consec_loss += 1
            consec_win = 0
            if consec_loss >= 3:
                halved = True
        else:
            consec_win += 1
            consec_loss = 0
            if halved and consec_win >= 2:
                halved = False
    return 0.5 if halved else 1.0


def _balance(mode: str, p: Dict) -> float:
    if mode == "live":
        return float(feed_state["account"].get("balance", 0) or 0)
    closed = storage.query_one(
        "SELECT COALESCE(SUM(pnl),0) s FROM trades WHERE mode='paper' AND status='closed'")
    return p["paper_balance"] + (closed["s"] if closed else 0)


# ------------------------------------------------------- signal exec
def _get_tv_ctx() -> Dict[str, Any]:
    """Return cached TV context; refresh at most once per hour."""
    global _tv_ctx, _tv_ctx_t
    if not _TV_AVAILABLE:
        return {}
    if time.time() - _tv_ctx_t > 3600:
        try:
            _tv_ctx = _tv.load()
            _tv_ctx_t = time.time()
        except Exception as e:
            print("tv_context load error:", e)
    return _tv_ctx


def _log_signal(sig: Dict, status: str, reason: str) -> int:
    return storage.execute(
        "INSERT INTO signals(t,symbol,trade_mode,side,grade,entry,sl,tp,rr,status,reason,setup,strategy) "
        "VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)",
        (int(time.time()), sig["symbol"], sig["trade_mode"], sig["side"], sig["grade"],
         sig["entry"], sig["sl"], sig["tp"], sig["rr"], status, reason,
         json.dumps(sig["setup"], default=str), sig.get("strategy", "slc")))


def try_execute(sig: Dict, p: Dict) -> None:
    mode = p["trading_mode"]
    symbol = sig["symbol"]
    strat = sig.get("strategy", "slc")
    a_class = instruments.asset_class(symbol)
    regime_ctx = {"atr_ratio": sig.get("regime")}

    # dedup: one shot per setup zone. Skipped signals only lock the zone
    # briefly (so e.g. "max concurrent" can retry once capacity frees);
    # executed ones lock it for 12 h.
    now = time.time()
    for k in list(_recent_keys):
        if _recent_keys[k] < now:
            del _recent_keys[k]
    if sig["key"] in _recent_keys:
        return

    def skip(reason: str, track: bool = False, stage: str = "rails",
             checks: Any = None) -> None:
        """track=True: the setup itself was valid but a risk/capacity filter
        blocked it -> also record it as a SHADOW trade so the outcome is
        studied (what did the filter cost or save us?)."""
        _recent_keys[sig["key"]] = time.time() + (12 * 3600 if track else 30 * 60)
        sig_id = _log_signal(sig, "skipped", reason)
        decisions.record(strat, symbol, sig["trade_mode"], stage, "skipped",
                         reason=reason, grade=sig["grade"], checks=checks,
                         regime=regime_ctx, signal_id=sig_id)
        if track and not any(t["symbol"] == symbol
                             for t in storage.open_trades("shadow")):
            storage.insert_trade({
                "mode": "shadow", "trade_mode": sig["trade_mode"], "symbol": symbol,
                "side": sig["side"], "status": "open", "grade": sig["grade"],
                "entry_time": int(time.time()), "entry": sig["entry"],
                "sl": sig["sl"], "initial_sl": sig["sl"],
                "tp1": sig["tp1"], "tp2": sig["tp"],
                "lots": 0.0, "risk_pct": 0.0, "risk_amount": 0.0,
                "setup": json.dumps({"skip_reason": reason, **sig["setup"]},
                                    default=str), "signal_id": 0,
                "strategy": strat, "asset_class": a_class,
            })
        if _notify and storage.get_setting("notify_signals", True):
            notify("⚠️ <b>Signal skipped</b> %s %s (%s)\n%s"
                   % (sig["side"].upper(), symbol, sig["trade_mode"], reason))

    # ---- fail-safe gates first (constraint 4: uncertainty halts entries) ----
    suspect = storage.integrity_suspect()
    if suspect:
        return skip("DB integrity suspect — failing safe: %s" % suspect,
                    stage="fail_safe")
    if p.get("halt_new_entries"):
        return skip("manual halt active (halt_new_entries)", stage="fail_safe")
    if mode == "off":
        return skip("trading mode is OFF", stage="mode")

    # ---- session calendar (never blocks crypto; see sessions.py) -----------
    open_ok, closed_reason = sessions.is_market_open(symbol)
    if not open_ok:
        return skip(closed_reason, stage="session")

    # ---- scheduled-news blackout (Phase 3; logs the exact event) -----------
    if _NEWS_CAL_AVAILABLE:
        blk = _news_cal.is_blackout(symbol)
        if blk:
            decisions.record(strat, symbol, sig["trade_mode"], "news", "skipped",
                             reason=blk["reason"], grade=sig["grade"],
                             regime=regime_ctx, news_ctx=blk)
            _news_cal.log_action(blk.get("event_id"), "block_entry", symbol,
                                 blk["reason"])
            _recent_keys[sig["key"]] = time.time() + 30 * 60
            _log_signal(sig, "skipped", blk["reason"])
            return

    all_open = storage.open_trades(mode)
    # max_concurrent is a PORTFOLIO limit, not a per-speed one. Counting only
    # trades of the same trade_mode meant intraday and swing each got their own
    # allowance: max_concurrent=2 with both speeds enabled permitted four open
    # positions, so 4% of open heat against a -2% daily stop. The kill switch
    # would fire before the concurrency rail ever did, which is backwards.
    if len(all_open) >= p["max_concurrent"]:
        return skip("max concurrent (%d) reached" % p["max_concurrent"],
                    track=True, stage="concurrency")
    if any(t["symbol"] == symbol for t in all_open):
        return skip("already in a %s trade" % symbol, track=True, stage="concurrency")
    by_class = exposure.class_concurrency(all_open)
    if by_class.get(a_class, 0) >= p["max_concurrent_per_class"]:
        return skip("max concurrent per asset class (%s: %d) reached"
                    % (a_class, p["max_concurrent_per_class"]),
                    track=True, stage="concurrency")
    same_dir = [t for t in all_open if t["side"] == sig["side"]]
    if len(same_dir) >= p["max_correlated"]:
        return skip("max correlated same-direction exposure (%d) reached"
                    % p["max_correlated"], track=True, stage="exposure")

    balance = _balance(mode, p)
    if balance <= 0:
        return skip("no balance data yet (is the EA pushing?)", stage="fail_safe")
    lim = loss_limits_hit(mode, balance, p)
    if lim:
        return skip(lim, track=True, stage="loss_limit")

    # Freshness and reachability only: this rail asks whether the quote is
    # usable, not which venue it came from. Where the order may go is the
    # separate question the routing rail below answers.
    price, px_reason = price_for_entry(symbol)
    if not price:
        return skip(px_reason, stage="feed")

    # ---- price provenance is bound to the execution venue -----------------
    # A signal priced by source S may only be executed on the venue that owns
    # S. Without this, a symbol routed to a crypto venue was sized off that
    # venue's book and then submitted to MT5 by the live branch below — a real
    # order, at the wrong broker, at a price that broker never showed.
    route = execution_route(symbol, price.get("src"), mode)
    if not route["ok"]:
        return skip(route["reason"], track=True, stage="routing")

    entry = price["ask"] if sig["side"] == "buy" else price["bid"]
    stop_dist = abs(entry - sig["sl"])
    spread = abs(price["ask"] - price["bid"])
    if stop_dist <= 0:
        return skip("price moved through SL before execution")
    if spread > p["max_spread_frac"] * stop_dist:
        return skip("spread %.5f > %.0f%% of stop distance" % (spread, p["max_spread_frac"] * 100))

    # price drifted from the analyzed signal -> setup geometry no longer valid
    if abs(entry - sig["entry"]) > 0.25 * stop_dist:
        return skip("price drifted %.5f from signal entry %.5f (>25%% of stop)"
                    % (entry, sig["entry"]))
    # re-check RR at the ACTUAL fill (drift + current spread)
    rr_actual = abs(sig["tp"] - entry) / stop_dist
    if rr_actual < p["min_rr"] * 0.9:
        return skip("RR at fill %.2f < required %.2f" % (rr_actual, p["min_rr"] * 0.9))

    risk_pct = p["risk_pct"] * (p["b_setup_risk_factor"] if sig["grade"] == "B" else 1.0)
    # consecutive-loss governor (playbook §10.3) and session risk factor
    # (e.g. crypto weekends) only ever REDUCE risk, never raise it
    gov = loss_governor(mode)
    sess_factor, sess_why = sessions.entry_risk_factor(symbol)
    if gov < 1.0:
        risk_pct *= gov
    if sess_factor < 1.0:
        risk_pct *= sess_factor

    # cross-asset factor-bucket exposure gate (lesson 1: EUR+DAX+Gold longs
    # are one stacked bet) — snapshot recorded on the decision either way
    exp_ok, exp_reason, exp_snapshot = exposure.check_candidate(
        symbol, sig["side"], risk_pct, all_open,
        p["max_bucket_exposure"], base_risk_pct=p["risk_pct"])
    if not exp_ok:
        return skip(exp_reason, track=True, stage="exposure", checks=exp_snapshot)

    risk_amount = balance * risk_pct / 100.0
    lots, actual_risk = calc_lots(symbol, entry, sig["sl"], risk_amount)
    if lots <= 0:
        return skip("could not size position (tick data missing)", stage="sizing")
    if actual_risk > risk_amount * 1.5:
        return skip("min lot would risk %.2f > 1.5x intended %.2f"
                    % (actual_risk, risk_amount), track=True, stage="sizing")
    risk_amount = actual_risk                       # record the TRUE risk
    risk_pct = round(risk_amount / balance * 100.0, 3)

    # TV context confluence (informational — does not block valid PA signals)
    tv_ctx = _get_tv_ctx()
    tv_score = _tv.confluence_score(tv_ctx, symbol, sig["side"].replace("buy","long").replace("sell","short")) \
        if _TV_AVAILABLE and tv_ctx else 0
    tv_regime = _tv.get_regime(tv_ctx, symbol) if _TV_AVAILABLE and tv_ctx else "unknown"
    tv_align  = _tv.direction_align(tv_ctx, symbol, sig["side"].replace("buy","long").replace("sell","short")) \
        if _TV_AVAILABLE and tv_ctx else None
    tv_rsi    = (tv_ctx.get(symbol) or {}).get("RSI")
    tv_adx    = (tv_ctx.get(symbol) or {}).get("ADX")

    _recent_keys[sig["key"]] = time.time() + 12 * 3600
    risk_notes = []
    if gov < 1.0:
        risk_notes.append("risk halved: 3+ consecutive losses (until 2 wins)")
    if sess_factor < 1.0:
        risk_notes.append(sess_why)
    enhanced_setup = dict(sig["setup"], tv_score=tv_score, tv_regime=tv_regime,
                          tv_align=tv_align, tv_rsi=round(tv_rsi, 1) if tv_rsi else None,
                          tv_adx=round(tv_adx, 1) if tv_adx else None)
    if risk_notes:
        enhanced_setup["risk_notes"] = risk_notes
    # Write-layer restatement of the routing rail: nothing may reach
    # insert_trade in live mode unless the EA is the cleared route, so a future
    # edit cannot produce an open live row with no order behind it.
    if mode == "live" and route.get("kind") != "mt5":
        return skip("live entry has no cleared execution route", track=True,
                    stage="routing")

    sig_id = _log_signal(sig, "executed", "")
    trade = {
        "mode": mode, "trade_mode": sig["trade_mode"], "symbol": symbol,
        "side": sig["side"], "status": "open", "grade": sig["grade"],
        "entry_time": int(time.time()), "entry": entry,
        "sl": sig["sl"], "initial_sl": sig["sl"], "tp1": sig["tp1"], "tp2": sig["tp"],
        "lots": lots, "risk_pct": risk_pct, "risk_amount": risk_amount,
        "setup": json.dumps(enhanced_setup, default=str), "signal_id": sig_id,
        "strategy": strat, "asset_class": a_class,
    }
    trade_id = storage.insert_trade(trade)
    decisions.record(strat, symbol, sig["trade_mode"], "execution", "executed",
                     reason="; ".join(risk_notes), grade=sig["grade"],
                     checks=exp_snapshot, features={"rr": sig["rr"], "lots": lots,
                                                    "risk_pct": risk_pct},
                     regime=regime_ctx, signal_id=sig_id, trade_id=trade_id)

    if mode == "live" and route.get("kind") == "mt5":
        # Only ever the EA. execution_route refused every other route above.
        storage.enqueue_command("open_trade", {
            "symbol": symbol, "side": sig["side"], "lots": lots,
            "sl": sig["sl"], "tp": sig["tp"], "magic": 770001,
            "comment": "SLC#%d" % trade_id,
            "reason": "SLC %s grade %s RR %.1f" % (sig["trade_mode"], sig["grade"], sig["rr"]),
        })

    # TV confluence line for notification
    tv_line = ""
    if tv_score is not None and tv_ctx:
        align_sym = "✅" if tv_align else "⚠️"
        tv_line = ("\nTV: %s score %d/4 | %s | RSI=%.0f ADX=%.0f"
                   % (align_sym, tv_score, tv_regime,
                      tv_rsi or 0, tv_adx or 0))

    notify(
        "🟢 <b>TRADE OPENED</b> (%s)\n"
        "<b>%s %s</b> — %s, grade %s\n"
        "Entry: <code>%.5f</code>\nSL: <code>%.5f</code>\n"
        "TP1: <code>%.5f</code>  TP2: <code>%.5f</code>\n"
        "Lots: %.2f | Risk: %.2f%% (%.2f) | RR: %.1f%s"
        % (mode.upper(), sig["side"].upper(), symbol, sig["trade_mode"], sig["grade"],
           entry, sig["sl"], sig["tp1"], sig["tp"], lots, risk_pct, risk_amount, sig["rr"],
           tv_line))


# ----------------------------------------- external signals (TradingView etc.)
def ingest_external_signal(symbol: str, fields: Dict[str, Any],
                           p: Dict[str, Any]) -> Dict[str, Any]:
    """Route a parsed external alert (e.g. a TradingView webhook) as a
    CANDIDATE through the SAME rails as an SLC signal — never a raw market
    order, never flips trading_mode. Builds an SLC-shaped sig (valid stop on the
    correct side, RR computed if absent) and hands it to `try_execute`, which
    applies the mode / stop / spread / drift / RR / concurrency / correlation /
    balance / loss-limit / sizing rails. Returns a status dict for the HTTP
    response. (Invariants checked: #6 candidates-not-orders, #3 stop side, #5
    risk cap via B sizing + the shared rails.)"""
    side = fields.get("side")
    if side not in ("buy", "sell"):
        return {"accepted": False, "reason": "missing/invalid side"}
    trade_mode = fields.get("trade_mode")
    if trade_mode not in MODE_TFS:
        trade_mode = "swing"

    price_info, _ = price_for_entry(symbol)
    live = None
    if price_info:
        live = price_info["ask"] if side == "buy" else price_info["bid"]

    entry = fields.get("entry")
    if entry is None:
        entry = live
    if entry is None:
        return {"accepted": False,
                "reason": "no entry in alert and no live price for %s" % symbol}
    entry = float(entry)

    sl = fields.get("sl")
    if sl is None:
        return {"accepted": False, "reason": "external signal must carry a stop"}
    sl = float(sl)
    # stop MUST be on the correct side of entry (never invent or flip it)
    if side == "buy" and not sl < entry:
        return {"accepted": False,
                "reason": "long stop %.6f not below entry %.6f" % (sl, entry)}
    if side == "sell" and not sl > entry:
        return {"accepted": False,
                "reason": "short stop %.6f not above entry %.6f" % (sl, entry)}

    risk = abs(entry - sl)
    if risk <= 0:
        return {"accepted": False, "reason": "degenerate risk distance"}

    tp = fields.get("tp")
    if tp is None:
        tp = entry + p["min_rr"] * risk if side == "buy" else entry - p["min_rr"] * risk
    tp = float(tp)
    if side == "buy" and not tp > entry:
        return {"accepted": False, "reason": "long target not above entry"}
    if side == "sell" and not tp < entry:
        return {"accepted": False, "reason": "short target not below entry"}

    tp1 = fields.get("tp1")
    tp1 = float(tp1) if tp1 is not None else (entry + risk if side == "buy" else entry - risk)
    rr = abs(tp - entry) / risk

    direction = "long" if side == "buy" else "short"
    src = str(fields.get("strategy") or "tradingview")
    sig = {
        "symbol": symbol, "trade_mode": trade_mode, "side": side,
        "strategy": "ext:%s" % src,
        # external alerts size as a B setup (b_setup_risk_factor, conservative);
        # they are vetted by the provider plus the bot's hard rails, not the SLC
        # quality checklist.
        "grade": "B",
        "entry": entry, "sl": sl, "tp1": tp1, "tp": tp,
        "rr": round(rr, 2), "atr": 0.0, "regime": 1.0, "spread": 0.0,
        "setup": {"source": "external", "provider": src, "trend": None,
                  "poi": None, "sweep": None, "confirmation": None},
        "key": "%s|%s|%s|%s|%.6f" % (src, symbol, trade_mode, direction, sl),
    }
    try_execute(sig, p)
    return {"accepted": True, "symbol": symbol, "side": side,
            "trade_mode": trade_mode, "rr": round(rr, 2),
            "mode": p["trading_mode"]}


# --------------------------------------------------- shadow tracking
def try_execute_shadow(sig: Dict, p: Dict) -> None:
    """Record a signal on a watch-only pair as a SHADOW trade: same entry
    rules and management as paper, but no money, no concurrency slot, no
    notifications. Pure sample collection for strategy evaluation."""
    symbol = sig["symbol"]
    now = time.time()
    if _recent_keys.get(sig["key"], 0) > now:
        return
    price, _ = price_for_entry(symbol)
    if not price:
        return
    entry = price["ask"] if sig["side"] == "buy" else price["bid"]
    stop_dist = abs(entry - sig["sl"])
    spread = abs(price["ask"] - price["bid"])
    if stop_dist <= 0 or spread > p["max_spread_frac"] * stop_dist:
        return
    if abs(entry - sig["entry"]) > 0.25 * stop_dist:
        return
    if abs(sig["tp"] - entry) / stop_dist < p["min_rr"] * 0.9:
        return
    _recent_keys[sig["key"]] = now + 12 * 3600
    sig_id = _log_signal(sig, "shadow", "watch-pair sample")
    trade_id = storage.insert_trade({
        "mode": "shadow", "trade_mode": sig["trade_mode"], "symbol": symbol,
        "side": sig["side"], "status": "open", "grade": sig["grade"],
        "entry_time": int(time.time()), "entry": entry,
        "sl": sig["sl"], "initial_sl": sig["sl"], "tp1": sig["tp1"], "tp2": sig["tp"],
        "lots": 0.0, "risk_pct": 0.0, "risk_amount": 0.0,
        "setup": json.dumps(sig["setup"], default=str), "signal_id": sig_id,
        "strategy": sig.get("strategy", "slc"),
        "asset_class": instruments.asset_class(symbol),
    })
    decisions.record(sig.get("strategy", "slc"), symbol, sig["trade_mode"],
                     "execution", "shadow", reason="watch-pair sample",
                     grade=sig["grade"], regime={"atr_ratio": sig.get("regime")},
                     signal_id=sig_id, trade_id=trade_id)


# --------------------------------------------------- open trade mgmt
def _close_paper(tr: Dict, price: float, reason: str) -> None:
    p = feed_state["prices"].get(tr["symbol"], {})
    tick_value = p.get("tick_value") or 0
    tick_size = p.get("tick_size") or 1
    direction = 1 if tr["side"] == "buy" else -1
    move = (price - tr["entry"]) * direction
    pnl = move / tick_size * tick_value * tr["lots"] if tick_size > 0 else 0
    # account for the half already banked at TP1 (valued from price distance)
    if tp1_partial_taken(tr):
        banked = abs(tr["entry"] - tr["initial_sl"]) / tick_size * tick_value * tr["lots"]
        pnl = pnl * 0.5 + banked * 0.5
    # Costs come off BEFORE the R-multiple is taken, because R is what the
    # promotion gate reads. A gate measuring gross R while live pays net is a gate
    # that certifies strategies which lose money.
    cost = round_turn_cost(tr, price)
    pnl -= cost

    risk_dist = abs(tr["entry"] - tr["initial_sl"])
    risk_amt = abs(risk_dist / tick_size * tick_value * tr["lots"]) if tick_size > 0 else 0
    if risk_amt > 0:
        r_mult = pnl / risk_amt                  # net R, straight from net money
    else:
        r_mult = (move / risk_dist) if risk_dist > 0 else 0
        if tp1_partial_taken(tr):
            r_mult = 0.5 * 1.0 + 0.5 * r_mult
    storage.update_trade(tr["id"], {
        "status": "closed", "exit_time": int(time.time()), "exit_price": price,
        "pnl": round(pnl, 2), "r_multiple": round(r_mult, 2), "exit_reason": reason,
        "costs": cost,
    })
    if tr["mode"] == "shadow":
        return                                  # silent sample collection
    emoji = "✅" if pnl >= 0 else "🔴"
    notify("%s <b>TRADE CLOSED</b> (PAPER)\n<b>%s %s</b> — %s\n"
           "Exit: <code>%.5f</code> | P&L: <b>%.2f</b> (%.2fR)\nReason: %s"
           % (emoji, tr["side"].upper(), tr["symbol"], tr["trade_mode"],
              price, pnl, r_mult, reason))


def _mtf_trail_level(tr: Dict) -> Optional[float]:
    tfs = MODE_TFS[tr["trade_mode"]]
    mtf = storage.get_bars(tr["symbol"], tfs["mtf"], 80)
    if len(mtf) < 10:
        return None
    pv = strategy.pivots(mtf, k=2)
    if tr["side"] == "buy":
        lows = [x["price"] for x in pv if x["kind"] == "L"]
        return lows[-1] if lows else None
    highs = [x["price"] for x in pv if x["kind"] == "H"]
    return highs[-1] if highs else None


# trade id -> the instant this position first went unevaluated. In-process
# only, and deliberately so: losing it on restart re-announces the outage,
# which is the safe direction. No risk state is derived from it.
_unmanaged: Dict[int, float] = {}


def _record_unmanaged(tr: Dict[str, Any], reason: str) -> None:
    """A position we hold and could NOT evaluate this cycle.

    This used to be a bare `continue`: no decisions row, no notification,
    nothing in _last_info. On a Linux node a missing quote is the ORDINARY
    failure mode, and a position whose stop is enforced only by this loop then
    runs unevaluated for the whole outage with nothing saying so. CONTRIBUTING
    requires a decisions.record for every decision including the decision not
    to act, and this is the one that costs money when it is missing."""
    tid = tr["id"]
    now = time.time()
    first = _unmanaged.get(tid)
    if first is None:
        first = _unmanaged[tid] = now
    _last_info["manage|%s" % tid] = {
        "symbol": tr["symbol"], "trade_mode": tr.get("trade_mode") or "—",
        "note": "%s %s #%s UNMANAGED for %.0fs: %s"
                % (tr["mode"], tr["symbol"], tid, now - first, reason)}
    # Deduped on (symbol, trade_mode, strategy, stage|reason): a transition log
    # rather than three identical rows a minute for the length of an outage.
    decisions.record_state(tr.get("strategy"), tr["symbol"],
                           tr.get("trade_mode") or "—", "manage", reason,
                           action="unmanaged", trade_id=tid)
    # Invariant 6: shadow trades are silent. They still get the audit row.
    if first == now and tr["mode"] != "shadow":
        notify("⚠️ <b>POSITION UNMANAGED</b> (%s)\n<b>%s %s</b> — stop is not "
               "being evaluated\nReason: %s"
               % (tr["mode"].upper(), tr["side"].upper(), tr["symbol"], reason))


def _clear_unmanaged(tr: Dict[str, Any]) -> None:
    """Management resumed on a position that had gone dark."""
    first = _unmanaged.pop(tr["id"], None)
    _last_info.pop("manage|%s" % tr["id"], None)
    if first is not None and tr["mode"] != "shadow":
        notify("🟩 <b>Management resumed</b> %s %s after %.0fs"
               % (tr["side"].upper(), tr["symbol"], time.time() - first))


def _held_at_mt5(tr: Dict[str, Any]) -> bool:
    """Is this live position held at MT5?

    Today every live position is — the EA is the only wired execution path —
    but gating EVERY live trade on the MT5 feed is the same global-bypass shape
    this branch exists to delete: the day one live position sits at a venue, a
    quiet EA would suspend its management too. A ticket is an MT5 ticket;
    failing that, the source quoting the symbol decides."""
    if tr.get("ticket"):
        return True
    return price_state(tr["symbol"]).get("source") == MT5_SOURCE


def manage_open_trades(p: Dict) -> None:
    """Runs EVERY cycle, per position, judged against the source that quotes
    THAT position. One venue going quiet must never suspend the stops on a
    position held somewhere else: standing aside from a new entry costs an
    opportunity, abandoning a stop costs the account."""
    open_trs = storage.open_trades()
    for tr in open_trs:
        st = price_state(tr["symbol"])
        price_info = st["price"]
        if not price_info:
            _record_unmanaged(tr, st["reason"] or "no usable quote")
            continue
        # A stale quote drops management into de-risk-only: the stop may still
        # act on it, nothing else may (docs/ARCHITECTURE-V3.md §2).
        derisk_only = not st["fresh"]
        bid, ask = price_info["bid"], price_info["ask"]
        cur = bid if tr["side"] == "buy" else ask          # exit side
        direction = 1 if tr["side"] == "buy" else -1
        risk_dist = abs(tr["entry"] - tr["initial_sl"])
        if risk_dist <= 0:
            # entry == initial_sl: an R-multiple cannot be computed, so every
            # level below is undefined. Bad data, not a benign skip.
            _record_unmanaged(tr, "entry equals initial stop — risk distance is "
                                  "zero, no level can be evaluated")
            continue
        r_now = (cur - tr["entry"]) * direction / risk_dist

        # track MFE / MAE in R — excursion measured off a dead quote is not an
        # excursion, it is the same number written down again
        upd: Dict[str, Any] = {}
        if not derisk_only:
            if r_now > (tr["mfe"] or 0):
                upd["mfe"] = round(r_now, 2)
            if r_now < (tr["mae"] or 0):
                upd["mae"] = round(r_now, 2)

        if tr["mode"] in ("paper", "shadow"):
            # Cleared here and not earlier: "we have a price" is not the same
            # as "we are managing it". The live branch below has two more gates
            # and clearing before them would flip-flop unmanaged/resumed every
            # cycle for the whole of an MT5 outage.
            _clear_unmanaged(tr)
            # Dynamic-spread stop: evaluate against the WORST exit-side price
            # seen on the 5s feed since the last cycle, not just this instant.
            w = feed_state.get("px_window", {}).get(tr["symbol"], {})
            worst_bid = min(bid, w.get("min_bid", bid))
            worst_ask = max(ask, w.get("max_ask", ask))
            max_spr = max(abs(ask - bid), w.get("max_spread", 0.0))
            max_spr_pts = w.get("max_spread_pts", price_info.get("spread", 0))
            rec = _open_spread.setdefault(tr["id"],
                                          {"symbol": tr["symbol"], "max_spread_pts": 0})
            if (max_spr_pts or 0) > rec["max_spread_pts"]:
                rec["max_spread_pts"] = max_spr_pts
            rec["cur_spread_pts"] = price_info.get("spread")
            sl_px = worst_bid if tr["side"] == "buy" else worst_ask
            hit_sl = (sl_px <= tr["sl"]) if tr["side"] == "buy" else (sl_px >= tr["sl"])
            hit_tp2 = (cur >= tr["tp2"]) if tr["side"] == "buy" else (cur <= tr["tp2"])
            if hit_sl:
                # did the SPREAD (not the mid) tag the stop?
                mid_ext = (worst_bid + max_spr / 2) if tr["side"] == "buy" \
                    else (worst_ask - max_spr / 2)
                spread_induced = (mid_ext > tr["sl"]) if tr["side"] == "buy" \
                    else (mid_ext < tr["sl"])
                _log_spread_event(tr, max_spr, max_spr_pts, spread_induced)
                if upd:
                    storage.update_trade(tr["id"], upd)
                base = "stop loss" if not tr["tp1_done"] else "trailing stop"
                reason = base + (" [spread-induced, max %.1fp]" % max_spr_pts
                                 if spread_induced else "")
                _close_paper(tr, tr["sl"], reason)
                continue
            if derisk_only:
                # Everything below books something OFF this quote: a TP2 fill, a
                # TP1 partial, a trail level recomputed from bars that stopped
                # arriving with it. All three flatter the sample the promotion
                # gate reads, and none of them can be confirmed until the source
                # comes back. The stop above is the exception because a breach
                # already printed and exits at tr["sl"] either way.
                continue
            if hit_tp2:
                if upd:
                    storage.update_trade(tr["id"], upd)
                _close_paper(tr, tr["tp2"], "take profit (TP2)")
                continue
            if not tr["tp1_done"] and r_now >= 1.0:
                upd["tp1_done"] = 1
                upd["sl"] = tr["entry"]                     # break-even
                if tr["mode"] == "paper":
                    notify("🔵 <b>TP1 hit</b> %s %s — 50%% banked, SL → breakeven"
                           % (tr["side"].upper(), tr["symbol"]))
            if tr["tp1_done"]:
                lvl = _mtf_trail_level(tr)
                if lvl is not None:
                    better = (lvl > tr["sl"]) if tr["side"] == "buy" else (lvl < tr["sl"])
                    in_profit = (lvl > tr["entry"]) if tr["side"] == "buy" else (lvl < tr["entry"])
                    if better and in_profit:
                        upd["sl"] = lvl
            if upd:
                storage.update_trade(tr["id"], upd)

        else:  # live: EA holds the position; we mirror + issue SL commands
            # This whole branch reasons over MT5's drop copy (open_positions,
            # closed_today) and issues MT5 commands, so it only applies to a
            # position MT5 actually holds. Gating it on the MT5 feed for EVERY
            # live trade regardless of venue is benign while live is EA-only —
            # and is exactly the global-bypass shape this branch exists to
            # remove, so it is scoped instead.
            if not _held_at_mt5(tr):
                _record_unmanaged(
                    tr, "live position is not held at MT5 and no venue "
                        "execution path is wired — cannot manage it from here")
                continue
            # On a stale drop copy the "position is gone -> it closed at the
            # broker" leg below would invent an exit for a trade still open.
            if not source_state(MT5_SOURCE)["fresh"]:
                _record_unmanaged(
                    tr, "MT5 drop copy stale — cannot confirm this position")
                continue
            _clear_unmanaged(tr)
            pos = next((x for x in feed_state["open_positions"]
                        if "SLC#%d" % tr["id"] in (x.get("comment") or "")
                        or x.get("ticket") == tr["ticket"]), None)
            if pos and not tr["ticket"]:
                upd["ticket"] = pos["ticket"]
            if pos:
                if not tr["tp1_done"] and r_now >= 1.0:
                    upd["tp1_done"] = 1
                    upd["sl"] = tr["entry"]
                    if tr["lots"] >= 0.02:        # 0.01 can't be halved
                        storage.enqueue_command("close_trade", {
                            "ticket": pos["ticket"], "lots": round(tr["lots"] / 2, 2),
                            "reason": "TP1 partial (1R)"})
                    storage.enqueue_command("trail_sl", {
                        "ticket": pos["ticket"], "symbol": tr["symbol"],
                        "new_sl": tr["entry"], "reason": "move to breakeven after TP1"})
                    notify("🔵 <b>TP1 hit</b> %s %s — partial close + BE sent to MT5"
                           % (tr["side"].upper(), tr["symbol"]))
                elif tr["tp1_done"]:
                    lvl = _mtf_trail_level(tr)
                    if lvl is not None:
                        better = (lvl > tr["sl"]) if tr["side"] == "buy" else (lvl < tr["sl"])
                        in_profit = (lvl > tr["entry"]) if tr["side"] == "buy" else (lvl < tr["entry"])
                        if better and in_profit:
                            upd["sl"] = lvl
                            storage.enqueue_command("trail_sl", {
                                "ticket": pos["ticket"], "symbol": tr["symbol"],
                                "new_sl": lvl, "reason": "structure trail"})
                if upd:
                    storage.update_trade(tr["id"], upd)
            else:
                # position no longer open at broker -> find the closing deal
                deal = next((d for d in feed_state["closed_today"]
                             if d.get("position_id") == tr["ticket"] and tr["ticket"]), None)
                exit_price = deal["price"] if deal else cur
                pnl = (deal["profit"] + deal.get("commission", 0) + deal.get("swap", 0)) \
                    if deal else 0.0
                r_mult = (exit_price - tr["entry"]) * direction / risk_dist
                storage.update_trade(tr["id"], {
                    "status": "closed", "exit_time": int(time.time()),
                    "exit_price": exit_price, "pnl": round(pnl, 2),
                    "r_multiple": round(r_mult, 2),
                    "exit_reason": "closed at broker"})
                emoji = "✅" if pnl >= 0 else "🔴"
                notify("%s <b>TRADE CLOSED</b> (LIVE)\n<b>%s %s</b>\n"
                       "Exit: <code>%.5f</code> | P&L: <b>%.2f</b> (%.2fR)"
                       % (emoji, tr["side"].upper(), tr["symbol"], exit_price, pnl, r_mult))

    # reset the spread window so the next cycle measures a fresh interval
    # (it re-accumulates from the very next 5s feed push)
    feed_state["px_window"] = {}
    open_ids = {t["id"] for t in open_trs}
    for _tid in list(_open_spread):
        if _tid not in open_ids:
            _open_spread.pop(_tid, None)
    for _tid in list(_unmanaged):
        if _tid not in open_ids:            # closed while dark; stop reporting it
            _unmanaged.pop(_tid, None)
            _last_info.pop("manage|%s" % _tid, None)
    try:
        import json as _json, os as _os
        _os.makedirs("state", exist_ok=True)
        with open("state/open_spread.json", "w") as _f:
            _json.dump({str(k): v for k, v in _open_spread.items()}, _f)
    except Exception as _e:
        print("open_spread dump error:", _e)


def manual_close(trade_id: int) -> bool:
    tr = storage.query_one("SELECT * FROM trades WHERE id=? AND status='open'", (trade_id,))
    if not tr:
        return False
    price_info = feed_state["prices"].get(tr["symbol"])
    if tr["mode"] == "paper":
        if not price_info:
            return False
        cur = price_info["bid"] if tr["side"] == "buy" else price_info["ask"]
        _close_paper(tr, cur, "manual close (dashboard)")
    else:
        if tr["ticket"]:
            storage.enqueue_command("close_trade", {
                "ticket": tr["ticket"], "lots": 0, "reason": "manual close (dashboard)"})
        else:
            storage.update_trade(trade_id, {
                "status": "closed", "exit_time": int(time.time()),
                "exit_reason": "manual close (no ticket linked)"})
    return True


# -------------------------------------------------------------- loop
def engine_loop(poll_seconds: int = 20) -> None:
    print("engine: started (poll %ds)" % poll_seconds)
    _stop.clear()
    while not _stop.is_set():
        try:
            # heartbeat EVERY cycle — even with every source dark — so the
            # dashboard can distinguish "engine process down" from "engine up,
            # no data" (both matter, differently)
            try:
                storage.set_setting("engine_heartbeat_t", int(time.time()))
                if feed_state.get("last_feed_t"):
                    storage.set_setting("ea_last_feed_t",
                                        int(feed_state["last_feed_t"]))
            except Exception:
                pass

            p = params()

            tradable = [s for s in p["enabled_pairs"] if s not in p["agent_disabled_pairs"]]
            shadow_only = [s for s in p["watch_pairs"] if s not in p["enabled_pairs"]]
            symbols = tradable + shadow_only

            # Tell the poller which symbols to keep priced, then move on. This
            # is a list assignment, not a network call: the venue poll happens
            # on its own thread precisely so manage_open_trades below never
            # waits behind an exchange. Positions on a symbol that has since
            # been disabled still need priced — a pair leaving the watchlist
            # must not strand the stop on a position it opened.
            held = {t["symbol"] for t in storage.open_trades()}
            set_venue_symbols(set(symbols) | held)
            if not _stop.is_set():
                start_venue_poller()

            # Feed health is now a per-source report, not one global verdict.
            # The loop never waits on it: work proceeds for every source that is
            # healthy, and the unhealthy ones lose their own symbols below.
            report = feed_report()
            _last_info["feed"] = {"symbol": "—", "trade_mode": "—",
                                  "note": report["note"]}

            manage_open_trades(p)

            mode = p["trading_mode"]
            balance = _balance(mode if mode != "off" else "paper", p)
            if balance > 0:
                if mode == "live":
                    eq = float(feed_state["account"].get("equity", balance) or balance)
                    storage.record_equity("live", balance, eq)
                else:
                    marked, unvalued = open_pnl_total()
                    if unvalued:
                        # Record NOTHING rather than a number that is wrong by an
                        # unknown amount. This series is the equity curve, and the
                        # drawdown forensics and the promotion gate read it; a
                        # sample that silently omits an underwater position is
                        # indistinguishable from a real one and cannot be
                        # corrected later. A gap in the curve is visible.
                        _last_info["equity"] = {
                            "symbol": "—", "trade_mode": "—",
                            "note": "equity sample skipped: %d open position%s "
                                    "cannot be valued (no fresh quote)"
                                    % (unvalued, "" if unvalued == 1 else "s")}
                    else:
                        storage.record_equity(mode if mode != "off" else "paper",
                                              balance, balance + marked)

            # broker clock offset (bar timestamps are broker time, not UTC)
            term = feed_state.get("terminal", {})
            tz_off = (term.get("time_local") or 0) - (term.get("time_utc") or 0)
            broker_now = time.time() + tz_off

            # Pre-warm TV context once per hour (non-blocking: uses cache if fresh)
            _get_tv_ctx()

            modes = [m for m in p["modes"] if m not in p["agent_disabled_modes"]]
            for symbol in symbols:
                # Per-symbol stand-aside, judged against the source that quotes
                # THIS symbol. Analyzing without a price it can be filled at only
                # produces "no live price" skips and 30-min zone locks, so the
                # symbol is dropped for this cycle — and only this symbol.
                price_info, feed_why = price_for_entry(symbol)
                if price_info is None:
                    note = "%s — standing aside on %s" % (feed_why, symbol)
                    for m in modes:
                        _last_info["%s|%s" % (symbol, m)] = {
                            "symbol": symbol, "trade_mode": m, "note": note}
                        decisions.record_state(None, symbol, m, "feed", note)
                    continue
                bars_by_tf = {tf: storage.get_bars(symbol, tf, 320)
                              for tf in ("15m", "30m", "1h", "2h", "4h", "1d")}
                spread = abs(price_info["ask"] - price_info["bid"])
                live_mid = (price_info["ask"] + price_info["bid"]) / 2
                for m in modes:
                    # don't analyze stale data: the newest setup-TF bar must
                    # have closed within the staleness limit for the symbol's
                    # asset class (broker clock; crypto is stricter — a gap in
                    # a 24/7 market means the feed died, not a weekend)
                    mtf_tf = MODE_TFS[m]["mtf"]
                    tf_sec = TF_SECONDS[mtf_tf]
                    mtf_bars = bars_by_tf.get(mtf_tf, [])
                    stale_lim = sessions.staleness_limit_s(symbol, tf_sec)
                    if mtf_bars and broker_now - (mtf_bars[-1]["t"] + tf_sec) > stale_lim:
                        note = ("bar data stale (last %s bar %dm old) — standing aside"
                                % (mtf_tf, (broker_now - mtf_bars[-1]["t"]) // 60))
                        _last_info["%s|%s" % (symbol, m)] = {
                            "symbol": symbol, "trade_mode": m, "note": note}
                        decisions.record_state(None, symbol, m, "fail_safe", note)
                        continue
                    # Strategies get a READ-ONLY view. try_execute reads its
                    # thresholds (risk_pct, the stops, the caps) out of this same
                    # dict, so a plugin holding a mutable reference could move a
                    # rail from outside the engine. SLCStrategy only reads, so this
                    # is behaviour-preserving; a plugin that writes now raises.
                    for sname, res in strategies.generate_all(
                            symbol, m, bars_by_tf, MappingProxyType(p),
                            spread=spread, live_price=live_mid):
                        res["info"]["watch"] = symbol in shadow_only
                        # one info row per symbol|mode|strategy (SLC-only keeps a
                        # single row per symbol|mode, now tagged with strategy)
                        _last_info["%s|%s|%s" % (symbol, m, sname)] = res["info"]
                        if not res["signal"]:
                            # audit the decision NOT to trade (deduped: only
                            # writes when the reason changes for this cell)
                            decisions.record_state(
                                sname, symbol, m, "analysis",
                                str(res["info"].get("note", "no setup")),
                                action="no_setup")
                        if res["signal"]:
                            res["signal"]["strategy"] = sname
                            if symbol in shadow_only:
                                # shadow trades that mirror an already-open shadow
                                # position on the same symbol are skipped
                                if not any(t["symbol"] == symbol
                                           for t in storage.open_trades("shadow")):
                                    try_execute_shadow(res["signal"], p)
                            else:
                                try_execute(res["signal"], p)
        except Exception as e:
            import traceback
            traceback.print_exc()
            print("engine error:", e)
        _stop.wait(poll_seconds)
    print("engine: stopped")
